In [2]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [30]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00004888
CPU times: user 466 μs, sys: 190 μs, total: 656 μs
Wall time: 613 μs


In [15]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 10, -15, -85,  -2, -96,  -3])

In [16]:
tenosr = torch.tensor([[0.1,0.2],[3,4],[5,6]])
tensor

tensor([[0.1000, 0.2000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])

In [17]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
empty = torch.empty(2,3)
empty

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [22]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [24]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [25]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [36]:
probabilities = torch.tensor([0.2,0.8])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 0, 1, 0, 1, 1, 1, 1])

In [37]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [38]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [42]:
out = torch.triu(torch.rand(4,5))
out

tensor([[0.7834, 0.8509, 0.1805, 0.6731, 0.3752],
        [0.0000, 0.0935, 0.3370, 0.1947, 0.2789],
        [0.0000, 0.0000, 0.3279, 0.8132, 0.2100],
        [0.0000, 0.0000, 0.0000, 0.9331, 0.5588]])

In [46]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [47]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [50]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [51]:
tens1 = torch.tensor([1,2,3])
tens2 = torch.tensor([4,5,6])
tens3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tens1,tens2,tens3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
linear(sample)

tensor([ 9.9072, -5.1375, -3.7840], grad_fn=<SqueezeBackward4>)

In [56]:
tensor = torch.tensor([1., 2., 3.])
softmax_output = F.softmax(tensor, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [57]:
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])
embedded_output = embedding(input_indices)

embedded_output

tensor([[ 1.1276, -0.6176, -0.4083,  0.8710, -0.0477, -0.6042],
        [-0.4515,  0.8489, -1.1039, -0.3439, -0.2583,  0.9338],
        [ 1.0790,  2.1136,  0.8300,  0.5687, -1.6536,  0.9083],
        [ 0.1654, -0.9665,  0.1419, -0.0742,  0.7178, -1.3295]],
       grad_fn=<EmbeddingBackward0>)

In [58]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
a@b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [65]:
int_64 = torch.randint(1, (3,2)).float()
print(int_64)
float_32 = torch.rand(2,3)
torch.matmul(int_64, float_32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [67]:
a = torch.rand(2, 3, 5)
print(a)
x, y, z = a.shape
a = a.view(y,x,z)
print(a)

tensor([[[0.0932, 0.8326, 0.6836, 0.5673, 0.6840],
         [0.0229, 0.1406, 0.5624, 0.0146, 0.2916],
         [0.4444, 0.5205, 0.9599, 0.3259, 0.5058]],

        [[0.2634, 0.0230, 0.8961, 0.1645, 0.8160],
         [0.1742, 0.5042, 0.1136, 0.9403, 0.4470],
         [0.2060, 0.0078, 0.9315, 0.4674, 0.9521]]])
tensor([[[0.0932, 0.8326, 0.6836, 0.5673, 0.6840],
         [0.0229, 0.1406, 0.5624, 0.0146, 0.2916]],

        [[0.4444, 0.5205, 0.9599, 0.3259, 0.5058],
         [0.2634, 0.0230, 0.8961, 0.1645, 0.8160]],

        [[0.1742, 0.5042, 0.1136, 0.9403, 0.4470],
         [0.2060, 0.0078, 0.9315, 0.4674, 0.9521]]])


In [5]:
x = torch.tensor([-0.05])
y = F.relu(x)
y

tensor([0.])

In [6]:
x = torch.tensor([-0.05])
y = F.sigmoid(x)
y

tensor([0.4875])

In [9]:
x = torch.tensor([-0.05])
y = F.tanh(x)
y

tensor([-0.0500])